// This file is auto-generated from Solidity source files. Do not edit manually.
// Generated by: bun run script/parse-events.ts

export const CONTRACT_EVENT_MAP = {
  Allocate: {
    Allocate: {
      hash: '0x2d453a8b2eb4888bfee5a5b17781ba95747a5f795cd81b44fe943773178f8d8e',
      args: [{type:"address",name:"master"},{type:"uint256",name:"allocated"},{type:"uint256",name:"masterShares"},{type:"address[]",name:"puppetList"},{type:"uint256[]",name:"matchedAmountList"},{type:"uint256[]",name:"shareList"},{type:"uint256",name:"balance"},{type:"uint256",name:"sharePrice"},{type:"uint256",name:"nonce"}]
    }
  },
  FeeMarketplace: {
    AcceptOffer: {
      hash: '0x7d778e14025c4611dae90acde3cdf239063797ccb4dc030ab8c78b43e4558e02',
      args: [{type:"address",name:"feeToken"},{type:"address",name:"buyer"},{type:"address",name:"receiver"},{type:"uint256",name:"payout"},{type:"uint256",name:"cost"}]
    },
    Deposit: {
      hash: '0xe09149d2123147c5f43d258257fef0b7b969db78269369ebcf5ebb9eef8592f2',
      args: [{type:"address",name:"feeToken"},{type:"address",name:"depositor"},{type:"uint256",name:"amount"}]
    }
  },
  Match: {
    SetFilter: {
      hash: '0xbd078dd032ec2100a860998c1f7e2df073bc372d108d3b913e943de8aec04dc9',
      args: [{type:"address",name:"puppet"},{type:"uint256",name:"dim"},{type:"bytes32",name:"value"},{type:"bool",name:"allowed"},{type:"bool",name:"filterInitialized"}]
    },
    SetPolicy: {
      hash: '0xcf09d97688624e8aaa0a521c63f07a43275782b762891376270588276aa06b84',
      args: [{type:"address",name:"puppet"},{type:"address",name:"master"},{type:"uint256",name:"allowanceRate"},{type:"uint256",name:"throttlePeriod"},{type:"uint256",name:"expiry"}]
    },
    Throttle: {
      hash: '0xdf2c4a07dae103ad7f59dca039b7d975217f99459f0e368cc5641e4c76fb7ca0',
      args: [{type:"address",name:"puppet"},{type:"address",name:"master"},{type:"uint256",name:"nextAllowedTimestamp"},{type:"uint256",name:"cappedAmount"}]
    }
  },
  Call: {
    MasterPostCall: {
      hash: '0x67fbceb6f2eabc4a751ff467dbfc905fd42e69581d0845a7f5611b9f79f09c1a',
      args: [{type:"address",name:"master"},{type:"address",name:"handler"},{type:"address",name:"baseToken"},{type:"uint256",name:"preBalance"},{type:"uint256",name:"postBalance"},{type:"bytes4",name:"actionType"},{type:"bytes32",name:"orderKey"},{type:"bytes32",name:"positionKey"},{type:"uint256",name:"pendingCount"}]
    },
    MasterPreCall: {
      hash: '0x389ee61ca1d49ba21f3520a970719e8437bcad42343b87b9af0a03c3455783ac',
      args: [{type:"address",name:"caller"},{type:"address",name:"master"},{type:"address",name:"handler"},{type:"bytes",name:"callData"}]
    },
    SetStage: {
      hash: '0x46bba7197d5e7af08dacd431dd788388211706a4472b21da0b1bd3b08ba558d9',
      args: [{type:"address",name:"target"},{type:"address",name:"oldStage"},{type:"address",name:"stage"}]
    },
    SettleOrders: {
      hash: '0x34e35d9c2270bbec97412cade1887c5ee3a88bb86c95a40f5b1e9ccbaffb4d2d',
      args: [{type:"address",name:"master"},{type:"bytes32[]",name:"orderKeyList"},{type:"uint256",name:"pendingCount"}]
    }
  },
  Registry: {
    CreateMaster: {
      hash: '0x84f532c220fa6acb8fb9d0ffdba204004c6f1edc207d2379b0ab021c2c2b4e9e',
      args: [{type:"address",name:"master"},{type:"address",name:"user"},{type:"address",name:"signer"},{type:"address",name:"baseToken"},{type:"bytes32",name:"name"}]
    },
    SetToken: {
      hash: '0xa1889ab2e3da12087e2d0d71b7c29f05459c1a316f34120bff7d5c6cbead6102',
      args: [{type:"bytes32",name:"tokenId"},{type:"address",name:"token"}]
    },
    SetTokenCap: {
      hash: '0x0eed9dd37bbcb01292183ae212328bd52aab55ce6eb475eb4fb6350de9286029',
      args: [{type:"address",name:"token"},{type:"uint256",name:"cap"}]
    }
  },
  TokenRouter: {
    Transfer: {
      hash: '0xf099cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9',
      args: [{type:"address",name:"sender"},{type:"address",name:"token"},{type:"address",name:"from"},{type:"address",name:"to"},{type:"uint256",name:"amount"}]
    }
  },
  Withdraw: {
    Withdraw: {
      hash: '0x8d7f87ab38a7f75a63dc465e10aadacecfca64c44ca774040b039bfb004e3367',
      args: [{type:"address",name:"user"},{type:"address",name:"master"},{type:"address",name:"token"},{type:"uint256",name:"shares"},{type:"uint256",name:"sharePrice"},{type:"uint256",name:"amount"},{type:"uint256",name:"nonce"}]
    }
  }
} as const
